embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
reasoning: 
  name: "llama-3.3-70b-versatile"
  task: "Reasoning"

teaching_model : 
  name: "deepseek-r1-distill-llama-70b"
  task: "Question Answering"

vectorstore:
  num_results: 5
  similarity_threshold: 0.5

data:
  folder_name : "Tutor/Data/Math/"